name: ANST Cypress RUN

on: [push]

jobs:
  cypress-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # Add these to generate Allure results
          # reporter: mocha-allure-reporter
          # reporterOptions: "configFile=allure-reporter.config.js"
          # Store results in the correct directory
          # working-directory: ./
          # # These help with Allure reporting
          # env: allure=true,allureResultsPath=allure-results

      - name: Generate Allure report
        if: always()
        run: |
          # npx allure generate allure-results --clean -o allure-report
          npx allure serve allure-results
          
      - name: Upload test results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: |
            allure-results/
            allure-report/
            cypress/videos/**/*.mp4
            cypress/screenshots/**/*.png
